controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_register:
  path: /inscription
  controller: App\Controller\RegistrationController::register
  methods: [GET, POST]

app_login:
  path: /connexion
  controller: App\Controller\SecurityController::login
  methods: [GET, POST]

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
  methods: [GET]